### ISSUE TITLE
Adopting ios 9.1

### ISSUE THREAD

**Issue by kos9kus** [Lightstreamer/utility-ThreadPool-ios#7]
By reason of The NSURLConnection got deprecated and there are no ways as use a NSURLSession.
The following question:  Are you going to re-write some muduls in favor of URLSession ?

**Comment by gianlucabertani** [comment]
This comes unexpected, I need some time to see what can be done.
Thanks for reporting.

**Comment by gianlucabertani** [comment]
Recently released version 1.6 includes support for NSURLSession: uses NSURLSession if it is available, and reverts to NSURLConnection when it is not (to ensure compatibility with iOS 5.1 and OS X 10.7, important for us).

Give it a try and let us know if if you should find any issues.
